import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Vamsi's Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className="!scroll-smooth h-screen snap-y snap-mandatory overflow-y-scroll overflow-x-hidden z-0 scrollbar-thumb-orange-500 scrollbar-track-[#242424] scrollbar-thin scrollbar-thumb-rounded-full scrollbar-track-rounded-full"
    >
      <body className={`bg-[#242424] text-white ${inter.className}`}>
        {children}
      </body>
    </html>
  );
}
